### ISSUE TITLE
Server-side aggregation

### ISSUE THREAD

**Issue by domoritz** [CMU-CREATE-Lab/esdr#81] opened 2024-02-28 05:45 UTC
It would be great we could aggregate time series in feeds by e.g. minutes, hours, or days. This would make it easier to load long time series in visualizations.

**Comment by chrisbartley** [comment] 2024-03-01 17:17
Agree, and it's something we've talked about for probably a decade.  It has more to do with the underlying datastore, however, so I'll add the feature request there.

**Comment by chrisbartley** [comment] 2024-03-01 17:18
Duplicate of https://github.com/BodyTrack/datastore/issues/11

**Closed as not planned by chrisbartley** 2024-03-01 17:18 UTC
